#!/bin/bash
# Adds the IMAP MCP Server to Claude Desktop config

CONFIG="$HOME/Library/Application Support/Claude/claude_desktop_config.json"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
SERVER_PATH="$PROJECT_DIR/src/index.ts"
TSX_BIN="$PROJECT_DIR/node_modules/.bin/tsx"
WRAPPER="$PROJECT_DIR/run.sh"

# Detect absolute path to node (works with fnm, nvm, etc.)
NODE_BIN="$(which node)"
if [ -z "$NODE_BIN" ]; then
  echo "❌ Could not find node. Make sure your Node version manager is active."
  exit 1
fi
NODE_DIR="$(dirname "$NODE_BIN")"
echo "✅ Found node at: $NODE_BIN"

# Create a wrapper script that injects the correct PATH
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Auto-generated by setup-claude.sh
export PATH="$NODE_DIR:\$PATH"
cd "$PROJECT_DIR"
exec "$TSX_BIN" "$SERVER_PATH"
EOF
chmod +x "$WRAPPER"
echo "✅ Created wrapper script at: $WRAPPER"

# Create config dir if needed
mkdir -p "$(dirname "$CONFIG")"

# If config doesn't exist yet, create a fresh one
if [ ! -f "$CONFIG" ]; then
  echo '{}' > "$CONFIG"
fi

# Backup existing config
cp "$CONFIG" "$CONFIG.bak"
echo "✅ Backed up existing config to $CONFIG.bak"

# Merge in the mail server entry using Node.js
node -e "
const fs = require('fs');
const config = JSON.parse(fs.readFileSync('$CONFIG', 'utf8'));

config.mcpServers = config.mcpServers || {};
config.mcpServers.mail = {
  command: '/bin/bash',
  args: ['$WRAPPER']
};

fs.writeFileSync('$CONFIG', JSON.stringify(config, null, 2));
console.log('✅ Mail MCP server added to Claude Desktop config');
"

echo ""
echo "👉 Now fully quit (Cmd+Q) and restart Claude Desktop."
